from .colors import *

CHRISTMAS_TREE = [
    OFF, OFF, OFF, GRN, GRN, OFF, OFF, OFF,
    OFF, OFF, OFF, GRN, YLW, OFF, OFF, OFF,
    OFF, OFF, GRN, BLU, GRN, GRN, OFF, OFF,
    OFF, GRN, YLW, GRN, GRN, YLW, GRN, OFF,
    OFF, OFF, GRN, GRN, GRN, GRN, OFF, OFF,
    OFF, GRN, YLW, GRN, BLU, GRN, GRN, OFF,
    GRN, BLU, GRN, GRN, GRN, YLW, GRN, GRN,
    OFF, OFF, OFF, BRN, BRN, OFF, OFF, OFF
]

HEART = [
    OFF, RED, RED, OFF, OFF, RED, RED, OFF,
    RED, RED, RED, RED, RED, RED, RED, RED,
    RED, RED, RED, RED, RED, RED, RED, RED,
    RED, RED, RED, RED, RED, RED, RED, RED,
    RED, WHI, RED, RED, RED, RED, RED, RED,
    OFF, RED, WHI, RED, RED, RED, RED, OFF,
    OFF, OFF, RED, RED, RED, RED, OFF, OFF,
    OFF, OFF, OFF, RED, RED, OFF, OFF, OFF
]