from .colors import *

FACEBOOK = [
    BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU,
    BLU, BLU, BLU, BLU, BLU, WHI, WHI, BLU,
    BLU, BLU, BLU, BLU, BLU, WHI, BLU, BLU,
    BLU, BLU, BLU, BLU, WHI, WHI, WHI, BLU,
    BLU, BLU, BLU, BLU, BLU, WHI, BLU, BLU,
    BLU, BLU, BLU, BLU, BLU, WHI, BLU, BLU,
    BLU, BLU, BLU, BLU, BLU, WHI, BLU, BLU,
    BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU
]

TWITTER = [
    BLU, OFF, OFF, OFF, OFF, BLU, OFF, OFF,
    BLU, BLU, OFF, OFF, BLU, BLU, BLU, OFF,
    BLU, BLU, BLU, BLU, BLU, BLU, BLU, BLU,
    BLU, BLU, BLU, BLU, BLU, BLU, BLU, OFF,
    OFF, BLU, BLU, BLU, BLU, BLU, BLU, OFF,
    OFF, OFF, BLU, BLU, BLU, BLU, OFF, OFF,
    OFF, BLU, BLU, BLU, BLU, OFF, OFF, OFF,
    BLU, BLU, BLU, OFF, OFF, OFF, OFF, OFF
]

YOUTUBE = [
    OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF,
    OFF, RED, RED, RED, RED, RED, RED, OFF,
    RED, RED, RED, WHI, RED, RED, RED, RED,
    RED, RED, RED, WHI, WHI, WHI, RED, RED,
    RED, RED, RED, WHI, WHI, WHI, RED, RED,
    RED, RED, RED, WHI, RED, RED, RED, RED,
    OFF, RED, RED, RED, RED, RED, RED, OFF,
    OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF
]